name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: node Settings 
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm i
    - run: npm run build 
    - run: npm test -- --watchAll=false

    - name: Builds Docker image
      run: docker build -t ecommerce:latest .
    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USUARIO }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Image
      run: docker push ecommerce
    
  deploy: 
    runs-on: ubuntu-latest
    name: deploy cd 
    needs: build
    steps: 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USUARIO }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          
